---
# only show filenames, at the top level
outputFormatters:
  - - markdownlint-cli2-formatter-pretty
    - appendLink: true
  - - markdownlint-cli2-formatter-summarize
    - byFile: true
gitignore: true
