---
version: 2
# sadly no color output due to https://github.com/readthedocs/readthedocs.org/issues/8733
mkdocs:
  fail_on_warning: true
  configuration: mkdocs.yml

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    - curl https://mise.run | sh
    - ~/.local/bin/mise settings experimental=true
    - ~/.local/bin/mise settings python.compile=false
    - ~/.local/bin/mise settings python.uv_venv_auto=true
    - ~/.local/bin/mise trust
    - ~/.local/bin/mise install
    - ~/.local/bin/mise exec --command "uv run tox run -e docs"
submodules:
  include: all
  recursive: true
