---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:41

dependencies:
  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  system:
    - openssh-clients
    - sshpass

  python:
    - boto3
    - botocore

  galaxy:
    collections:
      - ansible.scm
      - ansible.utils
      - community.general

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
