---
collection_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/.."
integration_tests_path: "{{ collection_root }}/tests/integration/targets/"
molecule_scenario_name: "{{ molecule_scenario_directory | basename }}"
